const constituencyData = [
    {
      id: 1,
      constituencyName: "Amberpet",
      mlaName: "Kaleru Venkatesh",
      mpName: "G. Kishan Reddy",
      corporatorName: "",
      location: {
        pincodes: [500013 , 
            500044,
            560041,
            500036,
            500027,
            500044],
        Latitude: "17.392",
        Longitude: "78.5163",
      },
    },
    {
      id: 2,
      constituencyName: "Jubilee Hills",
      mlaName: "Maganti Gopinath",
      mpName: "G. Kishan Reddy",
      corporatorName: "",
      location: {
        pincodes: [],
        Latitude: "17.4326",
        Longitude: "78.4071",
      },
    },
    {
      id: 3,
      constituencyName: "Khairatabad",
      mlaName: "Danam Nagender",
      mpName: "G. Kishan Reddy",
      corporatorName: "",
      location: {
        pincodes: [500004, 500045, 500004, 500034, 500004, 500022, 500082, 500004, 500041, 500073, 500038, 500045, 500063, 500029, 500027],
        Latitude: "17.4106",
        Longitude: "78.4652",
      },
    },
    {
      id: 4,
      constituencyName: "Musheerabad",
      mlaName: "Muta Gopal",
      mpName: "G. Kishan Reddy",
      corporatorName: "",
      location: {
        pincodes: [],
        Latitude: "17.4197",
        Longitude: "78.499",
      },
    },
    {
      id: 5,
      constituencyName: "Nampally",
      mlaName: "Jaffer Hussain Meraj",
      mpName: "G. Kishan Reddy",
      corporatorName: "",
      location: {
        pincodes: [],
        Latitude: "17.386041",
        Longitude: "78.466594",
      },
    },
    {
      id: 6,
      constituencyName: "Sanathnagar",
      mlaName: "Talasani Srinivas Yadav",
      mpName: "G. Kishan Reddy",
      corporatorName: "",
      location: {
        pincodes: [],
        Latitude: "17.4563",
        Longitude: "78.4439",
      },
    },
    {
      id: 7,
      constituencyName: "Secunderabad",
      mlaName: "Thigulla Padma Rao Goud",
      mpName: "G. Kishan Reddy",
      corporatorName: "",
      location: {
        pincodes: [],
        Latitude: "17.43993",
        Longitude: "78.498276",
      },
    },
    {
      id: 8,
      constituencyName: "Secunderabad Contonment",
      mlaName: "-",
      mpName: "G. Kishan Reddy",
      corporatorName: "",
      location: {
        pincodes: [],
        Latitude: "17.4430312",
        Longitude: "78.4895673",
      },
    },
    {
      id: 9,
      constituencyName: "Bahadurpura",
      mlaName: "Mohammad Moazam Khan",
      mpName: "Asaduddin Owaisi",
      corporatorName: "",
      location: {
        pincodes: [],
        Latitude: "17.357674",
        Longitude: "78.461906",
      },
    },
    {
      id: 10,
      constituencyName: "Chandrayanagutta",
      mlaName: "Akbaruddin Owaisi",
      mpName: "Asaduddin Owaisi",
      corporatorName: "",
      location: {
        pincodes: [],
        Latitude: "17.306159",
        Longitude: "78.473887",
      },
    },
    {
      id: 11,
      constituencyName: "Charminar",
      mlaName: "Mumtaz Ahmed Khan",
      mpName: "Asaduddin Owaisi",
      corporatorName: "",
      location: {
        pincodes: [],
        Latitude: "17.361431",
        Longitude: "78.474533",
      },
    },
    {
      id: 12,
      constituencyName: "Goshamahal",
      mlaName: "T. Raja Singh",
      mpName: "Asaduddin Owaisi",
      corporatorName: "",
      location: {
        pincodes: [],
        Latitude: "17.3813",
        Longitude: "78.4724",
      },
    },
    {
      id: 13,
      constituencyName: "Karwan",
      mlaName: "Kausar Mohiuddin",
      mpName: "Asaduddin Owaisi",
      corporatorName: "",
      location: {
        pincodes: [],
        Latitude: "17.3767",
        Longitude: "78.4388",
      },
    },
    {
      id: 14,
      constituencyName: "Malakpet",
      mlaName: "Ahmed bin Abdullah Balala",
      mpName: "Asaduddin Owaisi",
      corporatorName: "",
      location: {
        pincodes: [],
        Latitude: "17.3725",
        Longitude: "78.4896",
      },
    },
    {
      id: 15,
      constituencyName: "Yakatpura",
      mlaName: "Syed Ahmed Pasha Quadri",
      mpName: "Asaduddin Owaisi",
      corporatorName: "",
      location: {
        pincodes: [],
        Latitude: "17.3587",
        Longitude: "78.4859",
      },
    },
  ];
  
  export default constituencyData;
  